### ISSUE TITLE
Values are hard-coded

### ISSUE THREAD

**Issue by tomvachon** [RiotGames/cinq-auditor-cloudtrail#1]
There are values here which are hard coded around the trail name and such.  As such, it makes this unusable to anyone other than Riot unless they want "Riot" showing up all over

**Comment by markofu** [comment]
We will make this a config option @tomvachon.

**Comment by markofu** [comment]
@tomvachon fixed by https://github.com/RiotGames/cinq-auditor-cloudtrail/pull/2/commits/5fd4bc730767a9567e95e9da1d07b3143dd34522. Please confirm!

**Comment by markofu** [comment]
Fixed
